"""migrate_dates_to_datetime

Revision ID: 9cdeb178b880
Revises: f879c556f1ad
Create Date: 2026-04-01 18:14:23.403411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cdeb178b880'
down_revision: Union[str, None] = 'f879c556f1ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # NOTE: On PostgreSQL, the VARCHAR->TIMESTAMP conversion needs a USING clause.
    # Alembic's alter_column with postgresql_using handles this automatically.
    # For each alter_column below that changes VARCHAR to DateTime, PostgreSQL
    # will use: ALTER COLUMN col TYPE TIMESTAMP WITH TIME ZONE
    #           USING col::text::timestamp with time zone
    # SQLite ignores column type changes (types are advisory) so this is safe.
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='created_at::text::timestamp with time zone',
               existing_nullable=False)
    op.alter_column('accounts', 'updated_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='updated_at::text::timestamp with time zone',
               existing_nullable=False)
    op.alter_column('activities', 'occurred_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='occurred_at::text::timestamp with time zone',
               existing_nullable=False)
    op.alter_column('activities', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='created_at::text::timestamp with time zone',
               existing_nullable=False)
    op.alter_column('app_versions', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='created_at::text::timestamp with time zone',
               existing_nullable=False)
    op.alter_column('audit_log', 'timestamp',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='timestamp::text::timestamp with time zone',
               existing_nullable=False)
    op.alter_column('cfg_contact_roles', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='created_at::text::timestamp with time zone',
               existing_nullable=False)
    op.alter_column('cfg_contact_roles', 'updated_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='updated_at::text::timestamp with time zone',
               existing_nullable=False)
    op.alter_column('cfg_customer_types', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='created_at::text::timestamp with time zone',
               existing_nullable=False)
    op.alter_column('cfg_customer_types', 'updated_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='updated_at::text::timestamp with time zone',
               existing_nullable=False)
    op.alter_column('cfg_lead_sources', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='created_at::text::timestamp with time zone',
               existing_nullable=False)
    op.alter_column('cfg_lead_sources', 'updated_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='updated_at::text::timestamp with time zone',
               existing_nullable=False)
    op.alter_column('cfg_regions', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='created_at::text::timestamp with time zone',
               existing_nullable=False)
    op.alter_column('cfg_regions', 'updated_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='updated_at::text::timestamp with time zone',
               existing_nullable=False)
    op.alter_column('cfg_stage_probabilities', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='created_at::text::timestamp with time zone',
               existing_nullable=False)
    op.alter_column('cfg_stage_probabilities', 'updated_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='updated_at::text::timestamp with time zone',
               existing_nullable=False)
    op.alter_column('cfg_stages', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='created_at::text::timestamp with time zone',
               existing_nullable=False)
    op.alter_column('cfg_stages', 'updated_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='updated_at::text::timestamp with time zone',
               existing_nullable=False)
    op.alter_column('cfg_task_templates', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='created_at::text::timestamp with time zone',
               existing_nullable=False)
    op.alter_column('cfg_task_templates', 'updated_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='updated_at::text::timestamp with time zone',
               existing_nullable=False)
    op.alter_column('contact_channels', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='created_at::text::timestamp with time zone',
               existing_nullable=False)
    op.alter_column('contacts', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='created_at::text::timestamp with time zone',
               existing_nullable=False)
    op.alter_column('contacts', 'updated_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='updated_at::text::timestamp with time zone',
               existing_nullable=False)
    op.alter_column('opportunities', 'close_date',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='close_date::text::timestamp with time zone',
               existing_nullable=True)
    op.alter_column('opportunities', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='created_at::text::timestamp with time zone',
               existing_nullable=False)
    op.alter_column('opportunities', 'updated_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='updated_at::text::timestamp with time zone',
               existing_nullable=False)
    op.alter_column('targets', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='created_at::text::timestamp with time zone',
               existing_nullable=False)
    op.alter_column('targets', 'updated_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='updated_at::text::timestamp with time zone',
               existing_nullable=False)
    op.alter_column('tasks', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('tasks', 'opportunity_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tasks', 'account_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tasks', 'task_template_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tasks', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('tasks', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tasks', 'due_date',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('tasks', 'priority',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'medium'"))
    op.alter_column('tasks', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'open'"))
    op.alter_column('tasks', 'assigned_to_user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tasks', 'completed_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='completed_at::text::timestamp with time zone',
               existing_nullable=True)
    op.alter_column('tasks', 'completed_by_user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tasks', 'reminder_date',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='reminder_date::text::timestamp with time zone',
               existing_nullable=True)
    op.alter_column('tasks', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='created_at::text::timestamp with time zone',
               existing_nullable=False)
    op.alter_column('tasks', 'updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='updated_at::text::timestamp with time zone',
               existing_nullable=False)
    op.alter_column('users', 'last_login_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='last_login_at::text::timestamp with time zone',
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='created_at::text::timestamp with time zone',
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               postgresql_using='updated_at::text::timestamp with time zone',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('users', 'last_login_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('tasks', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('tasks', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('tasks', 'reminder_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks', 'completed_by_user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks', 'completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks', 'assigned_to_user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'open'"))
    op.alter_column('tasks', 'priority',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'medium'"))
    op.alter_column('tasks', 'due_date',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('tasks', 'task_template_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks', 'account_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks', 'opportunity_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('targets', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('targets', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('opportunities', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('opportunities', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('opportunities', 'close_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('contacts', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('contacts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('contact_channels', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('cfg_task_templates', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('cfg_task_templates', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('cfg_stages', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('cfg_stages', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('cfg_stage_probabilities', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('cfg_stage_probabilities', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('cfg_regions', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('cfg_regions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('cfg_lead_sources', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('cfg_lead_sources', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('cfg_customer_types', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('cfg_customer_types', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('cfg_contact_roles', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('cfg_contact_roles', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('audit_log', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('app_versions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('activities', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('activities', 'occurred_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('accounts', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('accounts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
